databases:
  - name: movie_theater_booking_db
    plan: free
    databaseName: movie_theater_booking
    user: movie_theater_booking_user
services:
  - type: web
    plan: free
    name: movie-theater-booking
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn movie_theater_booking.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie_theater_booking_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4